FIELDS_CONFIG:
  发包规范V1:
    master:
      iou:
        ProjectCode: [22.17, 1.33, 3.54, 2.11]
    page:
      "1":
        iou:
          DFM_Info:
            box: [14.44, 15.58, 4.15, 3.23]
            need_split: "\n"
            storage_var: ["", "engineer", "", "changing_date"]
    title:
      - first: "設備規格及參數"
        second: ""
        re:
          dev_max_size:
            match_key_string: "場地佔用"
            re_rule: "[場场]地[佔占]用.*[:：].*mm"
            match_rule: -1
          dev_failure_rate:
            match_key_string: "故障率"
            re_rule: "故障率\\s*[:：]\\s*(.*?)(?=\\n\\d+\\.|\\n\\s*$|\\n\\s*\\d+[\\.。]|\\Z)"
            match_rule: -1
          ComprehensiveCT:
            match_key_string: "綜合CT"
            re_rule: "[綜综]合[cC][Tt].*[:：]\\s*([\\d\\.]+[Ss]/[Pp][Cc][Ss].*?)\\s"
            match_rule: -1
          ComprehensiveUPH:
            match_key_string: "UPH"
            re_rule: "[Uu][Pp][Hh].*[:：].*([Pp][Cc][Ss]/[Hh])"
            match_rule: -1
          dev_overkill_rate:
            match_key_string: "過殺率"
            re_rule: "[過过][殺杀]率.*[(（][檢检][測测][設设][備备][)）][:：]\\s*([/\\d\\.%]+)"
            match_rule: -1
          dev_miss_rate:
            match_key_string: "漏檢率"
            re_rule: "漏[檢检]率.*[(（][檢检][測测][設设][備备][)）][:：]\\s*([/\\d\\.%]+)"
            match_rule: -1
          dev_operation_manpower:
            match_key_string: "機台操作人力"
            re_rule: "[机機]台操作人力\\s*[:：].*人/[机機]"
            match_rule: -1
      - first: "二.改造方案介紹及模組說明"
        second: "1.方案整體概況"
        re:
          img_dev_frontlooking:
            match_key_string: "4.長寬高尺寸,佔地面積"
            re_rule: "(?:\\d+[\\.。]\\s*)?[长長][宽寬]高尺寸\\s*[，,]\\s*[佔占]地面[積积][:：]"
            match_rule: 1
          img_dev_occupancy:
            match_key_string: "4.長寬高尺寸,佔地面積"
            re_rule: "(?:\\d+[\\.。]\\s*)?[长長][宽寬]高尺寸\\s*[，,]\\s*[佔占]地面[積积][:：]"
            match_rule: 5
          img_dev_overlooking:
            match_key_string: "3.俯視佈局圖"
            re_rule: "(?:\\d+[\\.。]\\s*)?俯[视視][布佈]局[图圖][:：]"
            match_rule: 1
      - first: "二.改造方案介紹及模組說明"
        second: "2.工藝流程"
        re:
          img_dev_craftsmanship:
            match_key_string: "工藝流程介紹"
            re_rule: "^\\s*(\\d+\\s*\\.?\\s*)?\\s*工\\s*[艺藝]\\s*流\\s*程\\s*介\\s*[绍紹]"
            match_rule: 1
      - first: "方案版本變更記錄"
        second: ""
        table:
          version:
            match_key_string: "報告版本\n（版本號+報告日期）"
          changing_description:
            match_key_string: "變更內容\n（需說明變更前和變更后內容對比）"
          release_date:
            match_key_string: "變更\n日期"